on:
  push:
    branches:
      - 'master'

jobs:
  write-git-info:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Update git info
      #   run: echo "${{ toJson(github.event.head_commit) }}"
        env:
          JSON: ${{ toJSON(github.event.head_commit) }}
        run: echo $JSON > .gitinfo
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
