on:
  push:
    branches:
      - 'master'

jobs:
  write-git-info:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Update git info
        run: |
          # echo "GITHUB_SHA ${GITHUB_SHA}"
          # echo "github.event.head_commit.message ${{ github.event.head_commit.message }}"
          echo "${{ toJson(github) }}"
      # Commit all changed files back to the repository
      # - uses: stefanzweifel/git-auto-commit-action@v4
